### ISSUE TITLE
_find_end problem

### ISSUE THREAD

**Issue by Sun-Kevin** [TrippW/LDF-Parser#3]
Hi there.

Thanks for providing this wonderful ldf-parser first.

However I have some problems while reading your codes. How the '_find_end' method locates the last '}' when there are maybe multiple '{' and '}' in Frames section?

**Comment by Sun-Kevin** [comment]
Sorta understood. Thx.

**Comment by TrippW** [comment]
Hi, it's been a while since I've worked on this actively. I'm pretty sure it counts the number of {s and }s until they are non-zero and equal. If the text goes {some_text}, then we have 1 { and 1 } (1,1). If it goes {some {other} {text} } we find two { before we find the first }, count is (2, 1). Then we find another { (3,1), then we find two }s which puts us at (3,3), which means we've found the end pair for the initial {. Hope that helps some.

**Comment by Sun-Kevin** [comment]
Thx. I have an another question though. Does this parser take comments into account?

**Comment by TrippW** [comment]
Honestly? It's been 2 years since I've had an LDF file to test the parser with. My immediate thought is no, but there's a chance it will ignore comments.
